//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XffDemo.Net47
{
    public partial class DefaultPage
    {
        protected global::System.Web.UI.WebControls.Literal LitEntry;
        protected global::System.Web.UI.WebControls.Literal LitHeaders;
    }
}
