//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XffDemo.Net47
{
    public partial class ReportsPage
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal LitTotal;
        protected global::System.Web.UI.WebControls.Literal LitBufferSize;
        protected global::System.Web.UI.WebControls.Literal LitUnique;
        protected global::System.Web.UI.WebControls.Literal LitWithXff;
        protected global::System.Web.UI.WebControls.Button BtnClear;
        protected global::System.Web.UI.WebControls.Literal LitTopIps;
        protected global::System.Web.UI.WebControls.Literal LitEntries;
    }
}
